# Generated by Django 5.2.4 on 2025-07-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Votante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ci', models.CharField(max_length=15, unique=True)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('direccion', models.TextField()),
                ('foto_ci_anverso', models.ImageField(upload_to='ci/anverso/')),
                ('foto_ci_reverso', models.ImageField(upload_to='ci/reverso/')),
                ('foto_votante', models.ImageField(upload_to='votantes/')),
                ('recinto_id', models.PositiveIntegerField()),
                ('recinto_nombre', models.CharField(max_length=255)),
            ],
        ),
    ]
