# Generated by Django 5.2.4 on 2025-07-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_padron', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='votante',
            name='mesa_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
