# Generated by Django 5.2.4 on 2025-07-08 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion_electoral', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recinto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=10)),
                ('partido', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=7)),
                ('candidato', models.CharField(max_length=100)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion_electoral.cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Papeleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generada', models.BooleanField(default=False)),
                ('candidaturas', models.ManyToManyField(to='administracion_electoral.candidatura')),
                ('eleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion_electoral.eleccion')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion_electoral.seccion')),
            ],
        ),
        migrations.CreateModel(
            name='MesaElectoral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('jurado_ids', models.JSONField(blank=True, default=list)),
                ('recinto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesas', to='administracion_electoral.recinto')),
            ],
        ),
    ]
